<?php
namespace App\Services;
use App\Models\InvoiceTestRel;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
class InventoryService {
 public function labId(object $u):int{$seen=[];while(!in_array((int)$u->role_id,[1,2],true)&&$u->creator_id&&!isset($seen[$u->id])){$seen[$u->id]=1;$u=DB::table('users')->find($u->creator_id)??$u;}return(int)$u->id;}
 public function consumeInitial(InvoiceTestRel $relation):void{if(!$relation->is_done||$this->empty($relation->result))return;$actor=auth()->user();DB::transaction(function()use($relation,$actor){$r=DB::table('invoice_test_rels')->lockForUpdate()->find($relation->id);if(!$r||!$r->is_done||$this->empty($r->result)||DB::table('inventory_runs')->where('invoice_test_rel_id',$r->id)->exists())return;$this->run($r,$actor,'initial',null,null,true);});}
 public function repeat(int $invoice,int $rel,object $actor,string $reason,string $request):object{return DB::transaction(function()use($invoice,$rel,$actor,$reason,$request){$lab=$this->labId($actor);if($x=DB::table('inventory_runs')->where('lab_id',$lab)->where('request_id',$request)->first())return$x;$r=DB::table('invoice_test_rels')->where('invoice_id_fk',$invoice)->lockForUpdate()->find($rel);if(!$r||!$r->is_done||$this->empty($r->result))throw ValidationException::withMessages(['analysis'=>'يجب اعتماد النتيجة قبل تسجيل إعادة التحليل.']);$i=DB::table('invoices')->find($invoice);abort_unless($i&&(int)$i->lab_id_fk===$lab,403);if(!DB::table('inventory_runs')->where('invoice_test_rel_id',$r->id)->exists())$this->run($r,$actor,'baseline',null,null,false);return$this->run($r,$actor,'repeat',$reason,$request,true);});}
 private function run(object $r,?object $actor,string $kind,?string $reason,?string $request,bool $consume):object{$i=DB::table('invoices')->find($r->invoice_id_fk);$lab=(int)$i->lab_id_fk;[$type,$sid,$name]=$this->subject($r);$seq=(int)DB::table('inventory_runs')->where('invoice_test_rel_id',$r->id)->max('sequence')+1;$rid=DB::table('inventory_runs')->insertGetId(['lab_id'=>$lab,'invoice_id'=>$i->id,'invoice_test_rel_id'=>$r->id,'sequence'=>$seq,'kind'=>$kind,'request_id'=>$request,'reason'=>$reason,'test_name'=>$name,'actor_id'=>$actor?->id,'actor_name'=>$actor?->name,'created_at'=>now()]);if(!$consume||!$type)return DB::table('inventory_runs')->find($rid);$bs=DB::table('inventory_bindings')->where(['lab_id'=>$lab,'subject_type'=>$type,'subject_id'=>$sid,'active'=>true])->get();foreach($bs as$b){$need=(int)$b->quantity;$ks=DB::table('inventory_kits')->where(['lab_id'=>$lab,'item_id'=>$b->item_id])->where('remaining','>',0)->where(fn($q)=>$q->whereNull('expires_on')->orWhereDate('expires_on','>=',now()->toDateString()))->orderByRaw('expires_on IS NULL')->orderBy('expires_on')->orderBy('id')->lockForUpdate()->get();if($ks->sum('remaining')<$need){$n=DB::table('inventory_items')->where('id',$b->item_id)->value('name');throw ValidationException::withMessages(['inventory'=>"المخزون غير كافٍ للمادة: $n"]);}foreach($ks as$k){if($need<=0)break;$take=min($need,(int)$k->remaining);$bal=(int)$k->remaining-$take;DB::table('inventory_kits')->where('id',$k->id)->update(['remaining'=>$bal,'updated_at'=>now()]);$p=$this->patient($i->patient_id_fk??null);DB::table('inventory_movements')->insert(['lab_id'=>$lab,'item_id'=>$b->item_id,'kit_id'=>$k->id,'run_id'=>$rid,'invoice_id'=>$i->id,'patient_id'=>$i->patient_id_fk??null,'patient_name'=>$p->name??null,'patient_code'=>$p->code??null,'test_name'=>$name,'kind'=>$kind,'quantity'=>-$take,'balance_after'=>$bal,'actor_id'=>$actor?->id,'actor_name'=>$actor?->name,'reason'=>$reason,'created_at'=>now()]);$need-=$take;}}return DB::table('inventory_runs')->find($rid);}
 private function subject(object$r):array{foreach(['test'=>'test_id_fk','culture'=>'culture_id_fk','package'=>'package_id_fk','test_group'=>'test_group_id_fk']as$t=>$f)if(!empty($r->$f)){$tb=$t==='test_group'?'test_groups':$t.'s';return[$t,(int)$r->$f,DB::table($tb)->where('id',$r->$f)->value('name')??$t];}return[null,null,'Analysis'];}
 private function patient(?int$id):?object{return$id?DB::table('patients')->leftJoin('users','users.id','=','patients.user_id')->where('patients.id',$id)->select('patients.code','users.name')->first():null;}
 private function empty(mixed$v):bool{return$v===null||trim((string)$v)===''||in_array(trim((string)$v),['[]','{}'],true);}
}