import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
await mkdir('test-results/accounting',{recursive:true});
const browser=await chromium.launch();const errors=[];
try{
 const page=await browser.newPage({viewport:{width:1440,height:1100}});
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:5173/tests/accounting-browser.html');
 await page.locator('[data-metric="total"]').waitFor();
 assert.equal(await page.locator('[data-metric="total"]').textContent(),'2,375,000');
 await page.screenshot({path:'test-results/accounting/dashboard-desktop.png',fullPage:true,animations:'disabled'});
 const tab=name=>page.locator('.ar-tabs').getByRole('button',{name,exact:true});
 await tab('إحالات المختبرات').click();await page.getByRole('button',{name:'عرض الفواتير: مختبر النور'}).click();
 await page.waitForFunction(()=>accountingFixture.requests.some(r=>r.url==='/accounting-reports'&&r.params.lab_referral_id===4));
 await page.getByRole('button',{name:'عرض الفاتورة: 1007011'}).click();
 const dialog=page.locator('dialog');await dialog.getByText('أحمد علي حسن',{exact:true}).waitFor();
 await dialog.getByText('مريم أحمد',{exact:true}).first().waitFor();await dialog.getByText('الدفعات المسجلة',{exact:true}).waitFor();await dialog.getByText('إضافة تسديد',{exact:true}).waitFor();
 await dialog.locator('summary').click();await dialog.getByText('Hemoglobin',{exact:false}).waitFor();
 await dialog.screenshot({path:'test-results/accounting/invoice-desktop.png',animations:'disabled'});
 await page.keyboard.press('Escape');await page.getByRole('button',{name:'التالي',exact:true}).click();await page.getByRole('button',{name:'عرض الفاتورة: 1007012'}).waitFor();
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'تصدير Excel',exact:true}).click();await download;
 assert.ok(await page.evaluate(()=>accountingFixture.requests.some(r=>r.url.endsWith('/export')&&r.params.lab_referral_id===4&&r.params.section==='invoices'&&!r.params.page)),'exports use applied filters and include all pages');
 const popupPromise=page.waitForEvent('popup');await page.getByRole('button',{name:'طباعة / حفظ PDF',exact:true}).click();const popup=await popupPromise;await popup.getByRole('heading',{name:'كشف الفواتير'}).waitFor();await popup.close();
 await tab('إحالات الأطباء').click();await page.getByRole('button',{name:'كشف الإحالات التفصيلي',exact:true}).click();await page.waitForFunction(()=>accountingFixture.store.filters.referral_type==='doctor'&&!accountingFixture.store.loading);
 await page.getByRole('button',{name:'إعادة ضبط',exact:true}).click();await page.waitForFunction(()=>!accountingFixture.store.loading);
 await tab('حركة التحصيل').click();await page.getByRole('button',{name:'عرض الفاتورة: 1007011'}).waitFor();
 await page.evaluate(()=>{accountingFixture.store.report.summary.profit_estimate=null;accountingFixture.store.report.summary.incomplete_profit_invoices=2;});assert.equal(await page.locator('[data-metric="profit_estimate"]').textContent(),'غير مكتمل');
 await tab('لوحة المتابعة').click();await page.setViewportSize({width:390,height:844});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=390),'dashboard does not overflow phone viewport');
 await page.screenshot({path:'test-results/accounting/dashboard-mobile.png',fullPage:true,animations:'disabled'});
 await tab('كشف الفواتير').click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=390),'wide invoice table scrolls within its own panel');
 await page.getByRole('button',{name:'عرض الفاتورة: 1007011'}).click();await dialog.getByText('أحمد علي حسن',{exact:true}).waitFor();const box=await dialog.boundingBox();assert.ok(box.x>=0&&box.x+box.width<=390,'invoice dialog fits phone');await dialog.screenshot({path:'test-results/accounting/invoice-mobile.png',animations:'disabled'});await page.getByRole('button',{name:'إغلاق تفاصيل الفاتورة'}).click();
 await page.evaluate(()=>{accountingFixture.empty=true;});await page.getByRole('button',{name:'تطبيق الفلاتر',exact:true}).click();await page.getByText('لا توجد سجلات تطابق هذه الفلاتر.',{exact:true}).waitFor();
 await page.evaluate(()=>{accountingFixture.fail=true;});await page.getByRole('button',{name:'تطبيق الفلاتر',exact:true}).click();await page.getByRole('alert').waitFor();assert.equal(await page.locator('[data-metric="total"]').count(),0,'old figures are cleared after failed filter application');
 await page.evaluate(()=>{accountingFixture.fail=false;accountingFixture.empty=false;});await page.getByRole('button',{name:'إعادة المحاولة',exact:true}).click();await page.locator('[data-metric="total"]').waitFor();
 assert.deepEqual(await page.evaluate(()=>accountingFixture.requests.filter(r=>r.method!=='get')),[],'report navigation is read-only');assert.deepEqual(errors,[]);
 console.log('PASS accounting desktop/mobile dashboard, referral drill-down, invoice audit, paging, complete filtered export, print popup, unknown-profit and failure/empty states');
}finally{await browser.close();}
