import { chromium } from 'playwright';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const browser = await chromium.launch();
const context = await browser.newContext({ viewport: { width: 1360, height: 960 }, acceptDownloads: true });
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await mkdir('test-results/activity', { recursive: true });
try {
  await page.goto('http://127.0.0.1:5173/tests/activity-browser.html');
  await page.getByRole('button', { name: 'تفاصيل السجل 1', exact: true }).waitFor();
  const desktop = await page.screenshot({ path:'test-results/activity/desktop.jpg', type:'jpeg', quality:55 });
  await page.getByRole('button', { name: 'تفاصيل السجل 1', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByRole('cell', { name:'15', exact:true }).waitFor();
  assert.equal(await dialog.getByRole('cell', { name:'10', exact:true }).count(), 1);
  assert.match(await dialog.innerText(), /CBC/);
  assert.match(await dialog.innerText(), /الفاتورة #42/);
  assert.equal(await dialog.locator('th').nth(1).innerText(), 'شنو جان — قبل');
  assert.equal(await dialog.locator('th').nth(2).innerText(), 'شنو صار — بعد');
  await page.screenshot({ path:'test-results/activity/comparison.jpg', type:'jpeg', quality:65 });
  await page.keyboard.press('Escape');
  await dialog.waitFor({ state:'hidden' });
  assert.equal(await page.getByRole('button', { name:'تفاصيل السجل 1', exact:true }).evaluate(el => el === document.activeElement), true);
  await page.getByLabel('رقم الفاتورة', { exact:true }).fill('42');
  await page.getByRole('button', { name:'تطبيق الفلاتر', exact:true }).click();
  await page.getByRole('button', { name:'التالي', exact:true }).click();
  await page.getByRole('button', { name:'تفاصيل السجل 2', exact:true }).waitFor();
  const last = await page.evaluate(() => window.auditRequests.filter(r => r.url === '/activity/show').at(-1));
  assert.equal(Number(last.params.invoice_id), 42); assert.equal(last.params.page, 2);
  const [download] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name:'تصدير التقرير المفصّل', exact:true }).click()]);
  assert.match(download.suggestedFilename(), /^activity-report-.*\.csv$/);
  const exported = await page.evaluate(() => window.auditRequests.find(r => r.url === '/activity/export'));
  assert.equal(Number(exported.params.invoice_id), 42);
  await page.evaluate(() => {
    const row = document.createElement('div'); row.dataset.auditInvoiceId = '42';
    const button = document.createElement('button'); button.textContent = 'حفظ تجريبي'; button.onclick = window.syntheticMutation;
    row.appendChild(button); document.body.appendChild(row);
  });
  await page.getByRole('button', { name:'حفظ تجريبي', exact:true }).click();
  await page.waitForFunction(() => window.uiActions.some(a => a.label === 'حفظ تجريبي'));
  const correlation = await page.evaluate(() => ({ click:window.uiActions.find(a => a.label === 'حفظ تجريبي'), request:window.auditRequests.find(r => r.url === '/invoices/send') }));
  assert.equal(correlation.click.invoice_id, 42);
  assert.equal(correlation.request.headers['X-Audit-Action-Id'], correlation.click.action_id);
  assert.equal(decodeURIComponent(correlation.request.headers['X-Audit-Label']), 'حفظ تجريبي');
  assert.deepEqual(Object.keys(correlation.click).sort(), ['action_id', 'invoice_id', 'label', 'page']);
  await page.getByLabel('رقم الفاتورة', { exact:true }).fill('9999');
  await page.getByRole('button', { name:'تطبيق الفلاتر', exact:true }).click();
  await page.getByText('لا توجد حركات مطابقة للفلاتر.').waitFor();
  await page.getByRole('button', { name:'مسح الفلاتر', exact:true }).click();
  await page.getByRole('button', { name:'تفاصيل السجل 1', exact:true }).waitFor();
  await page.setViewportSize({ width:390, height:844 });
  await page.screenshot({ path:'test-results/activity/mobile.jpg', type:'jpeg', quality:65, fullPage:true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'page contains its horizontal table scroll on mobile');
  assert.deepEqual(errors, []);
  console.log('PASS activity details, values, invoice filters, pagination, export, mobile layout, focus restoration and click correlation');
  console.log('AUDIT_DESKTOP_IMAGE:' + desktop.toString('base64'));
} catch (error) {
  await page.screenshot({ path:'test-results/activity/failure.png', fullPage:true });
  throw error;
} finally { await browser.close(); }
