import { chromium } from 'playwright';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const out = 'test-results/lab-notifications';
await mkdir(out, {recursive:true});
const browser = await chromium.launch();
const errors=[];
try {
 const page=await browser.newPage({viewport:{width:1360,height:1000}});
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:5173/tests/lab-notifications-browser.html');
 await page.getByRole('button',{name:'حفظ إعدادات الإشعارات',exact:true}).waitFor();
 await page.screenshot({path:out+'/settings-desktop.png',fullPage:true});
 await page.getByRole('switch',{name:'تنبيه جاهزية النتائج تلقائياً',exact:true}).uncheck();
 await page.getByRole('button',{name:'حفظ إعدادات الإشعارات',exact:true}).click();
 await page.getByText('تم حفظ إعدادات إشعارات المختبر.',{exact:true}).waitFor();
 assert.equal(await page.evaluate(()=>notificationMock.settings.results_enabled),false);
 await page.getByRole('switch',{name:'تنبيه جاهزية النتائج تلقائياً',exact:true}).check();
 await page.getByRole('button',{name:'حفظ إعدادات الإشعارات',exact:true}).click();
 await page.getByRole('button',{name:'إرسال إشعار',exact:true}).click();
 await page.getByLabel('نوع الإشعار',{exact:true}).selectOption('test');
 await page.getByLabel('المريض المشترك',{exact:true}).selectOption('81');
 await page.getByLabel('عنوان الرسالة',{exact:true}).fill('تجربة إشعارات المختبر');
 await page.getByLabel('نص الرسالة',{exact:true}).fill('هذا إشعار تجريبي من مختبر إزمير.');
 await page.getByRole('button',{name:'مراجعة الرسالة والمستلمين',exact:true}).click();
 assert.equal(await page.evaluate(()=>notificationMock.posts.length),0,'preview must not send');
 await page.evaluate(()=>notificationMock.failOnce=true);
 await page.getByRole('button',{name:'تأكيد وإرسال الإشعار',exact:true}).click();
 await page.getByRole('alert').waitFor();
 assert.match(page.url(), /lab-notifications-browser\.html$/, 'temporary failure must preserve the mounted draft');
 await page.getByRole('button',{name:'تأكيد وإرسال الإشعار',exact:true}).click();
 await page.getByText('أُضيف الطلب لطابور الإرسال. ستظهر المحاولات في السجل.',{exact:true}).waitFor();
 const requests=await page.evaluate(()=>notificationMock.posts);
 assert.equal(requests.length,2);assert.equal(requests[0].request_id,requests[1].request_id,'failed response retry preserves idempotency key');
 assert.equal(requests[1].patient_id,81);assert.equal(requests[1].audience,'patient');
 await page.getByRole('button',{name:'سجل الإرسال',exact:true}).click();
 await page.getByRole('button',{name:'تفاصيل المحاولات',exact:true}).click();
 await page.getByText('تعذر الاتصال بخدمة الإشعارات',{exact:true}).waitFor();
 await page.getByRole('button',{name:'إعادة المحاولات الفاشلة',exact:true}).click();
 assert.equal(await page.evaluate(()=>notificationMock.retry),1);
 await page.getByRole('button',{name:'إيقاف المتبقي',exact:true}).click();
 await page.getByText('أُوقف ما تبقى من الحملة.',{exact:true}).waitFor();
 assert.equal(await page.evaluate(()=>notificationMock.cancelled),1);
 await page.screenshot({path:out+'/history-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 for(const [tab,file] of [['الإعدادات','settings-mobile'],['إرسال إشعار','send-mobile'],['سجل الإرسال','history-mobile']]){
   await page.getByRole('button',{name:tab,exact:true}).click();
   assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'no horizontal overflow: '+tab);
   await page.screenshot({path:out+'/'+file+'.png',fullPage:true});
 }
 await page.goto('http://127.0.0.1:5173/tests/lab-notifications-browser.html?admin=1');
 await page.getByLabel('المختبر',{exact:true}).waitFor();
 assert.equal(await page.getByRole('button',{name:'حفظ إعدادات الإشعارات',exact:true}).count(),0,'admin must select a lab explicitly');
 await page.getByLabel('المختبر',{exact:true}).selectOption('24');
 await page.getByRole('button',{name:'حفظ إعدادات الإشعارات',exact:true}).waitFor();
 await page.getByRole('button',{name:'حفظ إعدادات الإشعارات',exact:true}).click();
 assert.equal(await page.evaluate(()=>notificationMock.saves.at(-1).lab_id),'24');
 assert.deepEqual(errors,[]);
 console.log('PASS owner settings, preview, single-patient send, safe retry, history, cancellation, responsive layout and explicit admin scope');
} finally { await browser.close(); }
