<?php
namespace App\Http\Controllers;
use App\Services\InventoryService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
class InventoryController extends Controller {
 public function __construct(private InventoryService $inventory){}
 private function lab(Request$r):int{$u=$r->user();$lab=$this->inventory->labId($u);if((int)$u->role_id===1&&$r->filled('lab_id')){$x=(int)$r->integer('lab_id');abort_unless(DB::table('users')->where('id',$x)->whereIn('role_id',[1,2])->exists(),422);$lab=$x;}return$lab;}
 private function allow(Request$r,string$p):void{abort_unless($r->user()->can($p)||in_array((int)$r->user()->role_id,[1,2],true),403);}
 public function options(Request$r){$this->allow($r,'inventory view');$lab=$this->lab($r);$s=[];foreach(['test'=>'tests','culture'=>'cultures','package'=>'packages','test_group'=>'test_groups']as$t=>$tb)$s[$t]=DB::table($tb)->where('lab_id_fk',$lab)->whereNull('deleted_at')->orderBy('name')->get(['id','name']);return['lab_id'=>$lab,'subjects'=>$s];}
 public function index(Request$r){$this->allow($r,'inventory view');$lab=$this->lab($r);$items=DB::table('inventory_items as i')->where('i.lab_id',$lab)->leftJoin('inventory_kits as k','k.item_id','=','i.id')->groupBy('i.id','i.name','i.unit','i.low_stock_threshold','i.created_at','i.updated_at')->select('i.*')->selectRaw('COALESCE(SUM(CASE WHEN k.remaining > 0 AND (k.expires_on IS NULL OR k.expires_on >= CURDATE()) THEN k.remaining ELSE 0 END),0) available')->orderBy('i.name')->get();$kits=DB::table('inventory_kits as k')->join('inventory_items as i','i.id','=','k.item_id')->where('k.lab_id',$lab)->select('k.*','i.name as item_name','i.unit')->orderByDesc('k.id')->get();$bindings=DB::table('inventory_bindings as b')->join('inventory_items as i','i.id','=','b.item_id')->where('b.lab_id',$lab)->select('b.*','i.name as item_name')->orderByDesc('b.id')->get();return compact('items','kits','bindings');}
 public function storeItem(Request$r){$this->allow($r,'inventory manage');$lab=$this->lab($r);$v=$r->validate(['name'=>['required','string','max:150',Rule::unique('inventory_items')->where('lab_id',$lab)],'unit'=>'required|string|max:40','low_stock_threshold'=>'required|integer|min:0|max:1000000']);$v+=['lab_id'=>$lab,'created_at'=>now(),'updated_at'=>now()];return response()->json(DB::table('inventory_items')->find(DB::table('inventory_items')->insertGetId($v)),201);}
 public function receiveKit(Request$r){$this->allow($r,'inventory manage');$lab=$this->lab($r);$v=$r->validate(['item_id'=>['required','integer',Rule::exists('inventory_items','id')->where('lab_id',$lab)],'serial_number'=>['required','string','max:120',Rule::unique('inventory_kits')->where('lab_id',$lab)],'lot_number'=>'nullable|string|max:120','expires_on'=>'nullable|date|after_or_equal:today','capacity'=>'required|integer|min:1|max:1000000']);return DB::transaction(function()use($v,$lab,$r){$id=DB::table('inventory_kits')->insertGetId($v+['lab_id'=>$lab,'remaining'=>$v['capacity'],'created_at'=>now(),'updated_at'=>now()]);DB::table('inventory_movements')->insert(['lab_id'=>$lab,'item_id'=>$v['item_id'],'kit_id'=>$id,'kind'=>'receipt','quantity'=>$v['capacity'],'balance_after'=>$v['capacity'],'actor_id'=>$r->user()->id,'actor_name'=>$r->user()->name,'created_at'=>now()]);return response()->json(['id'=>$id],201);});}
 public function storeBinding(Request$r){$this->allow($r,'inventory manage');$lab=$this->lab($r);$v=$r->validate(['subject_type'=>'required|in:test,culture,package,test_group','subject_id'=>'required|integer','item_id'=>['required','integer',Rule::exists('inventory_items','id')->where('lab_id',$lab)],'quantity'=>'required|integer|min:1|max:1000','active'=>'sometimes|boolean']);$tb=$v['subject_type']==='test_group'?'test_groups':$v['subject_type'].'s';abort_unless(DB::table($tb)->where('id',$v['subject_id'])->where('lab_id_fk',$lab)->exists(),422);DB::table('inventory_bindings')->updateOrInsert(['lab_id'=>$lab,'subject_type'=>$v['subject_type'],'subject_id'=>$v['subject_id'],'item_id'=>$v['item_id']],['quantity'=>$v['quantity'],'active'=>$v['active']??true,'updated_at'=>now(),'created_at'=>now()]);return['message'=>'تم حفظ الربط'];}
 public function adjustKit(Request$r,int$kit){$this->allow($r,'inventory manage');$lab=$this->lab($r);$v=$r->validate(['quantity'=>'required|integer|not_in:0','reason'=>'required|string|min:5|max:500','expected_remaining'=>'required|integer|min:0']);return DB::transaction(function()use($kit,$lab,$v,$r){$k=DB::table('inventory_kits')->where('lab_id',$lab)->lockForUpdate()->find($kit);abort_unless($k,404);abort_if((int)$k->remaining!==(int)$v['expected_remaining'],409,'تم تعديل الرصيد من مستخدم آخر.');$n=(int)$k->remaining+(int)$v['quantity'];abort_unless($n>=0&&$n<=(int)$k->capacity,422,'الرصيد خارج سعة الكت.');DB::table('inventory_kits')->where('id',$kit)->update(['remaining'=>$n,'updated_at'=>now()]);DB::table('inventory_movements')->insert(['lab_id'=>$lab,'item_id'=>$k->item_id,'kit_id'=>$kit,'kind'=>'adjustment','quantity'=>$v['quantity'],'balance_after'=>$n,'actor_id'=>$r->user()->id,'actor_name'=>$r->user()->name,'reason'=>$v['reason'],'created_at'=>now()]);return['remaining'=>$n];});}
 private function q(Request$r,int$lab){return DB::table('inventory_movements as m')->join('inventory_items as i','i.id','=','m.item_id')->join('inventory_kits as k','k.id','=','m.kit_id')->where('m.lab_id',$lab)->when($r->filled('from'),fn($q)=>$q->whereDate('m.created_at','>=',$r->from))->when($r->filled('to'),fn($q)=>$q->whereDate('m.created_at','<=',$r->to))->when($r->filled('kind'),fn($q)=>$q->where('m.kind',$r->kind))->when($r->filled('search'),function($q)use($r){$s='%'.$r->search.'%';$q->where(fn($x)=>$x->where('m.patient_name','like',$s)->orWhere('m.patient_code','like',$s)->orWhere('m.test_name','like',$s)->orWhere('k.serial_number','like',$s));})->select('m.*','i.name as item_name','i.unit','k.serial_number','k.lot_number');}
 public function report(Request$r){$this->allow($r,'inventory reports');$q=$this->q($r,$this->lab($r));return['rows'=>$q->orderByDesc('m.created_at')->paginate(50)];}
 public function export(Request$r){$this->allow($r,'inventory reports');$rows=$this->q($r,$this->lab($r))->orderByDesc('m.created_at')->get();return response()->streamDownload(function()use($rows){$f=fopen('php://output','w');fputs($f,"\xEF\xBB\xBF");fputcsv($f,['التاريخ','المادة','السيريال','المريض','الكود','التحليل','الحركة','الكمية','الرصيد','المستخدم','السبب']);foreach($rows as$x){$s=fn($v)=>preg_match('/^[=+\-@]/',(string)$v)?"'".$v:$v;fputcsv($f,[$x->created_at,$s($x->item_name),$s($x->serial_number),$s($x->patient_name),$s($x->patient_code),$s($x->test_name),$x->kind,$x->quantity,$x->balance_after,$s($x->actor_name),$s($x->reason)]);}fclose($f);},'inventory-report.csv',['Content-Type'=>'text/csv; charset=UTF-8']);}
 public function invoice(Request$r,int$invoice){$this->allow($r,'inventory view');$lab=$this->lab($r);abort_unless(DB::table('invoices')->where('id',$invoice)->where('lab_id_fk',$lab)->exists(),404);$relations=DB::table('invoice_test_rels')->where('invoice_id_fk',$invoice)->get()->map(function($x){foreach(['test'=>'test_id_fk','culture'=>'culture_id_fk','package'=>'package_id_fk','test_group'=>'test_group_id_fk']as$t=>$f)if($x->$f){$tb=$t==='test_group'?'test_groups':$t.'s';$x->analysis_name=DB::table($tb)->where('id',$x->$f)->value('name');break;}$x->runs=DB::table('inventory_runs')->where('invoice_test_rel_id',$x->id)->orderBy('sequence')->get();return$x;});return['relations'=>$relations,'movements'=>$this->q(new Request(),$lab)->where('m.invoice_id',$invoice)->orderByDesc('m.created_at')->get()];}
 public function repeat(Request$r,int$invoice){$this->allow($r,'inventory repeat');$v=$r->validate(['invoice_test_rel_id'=>'required|integer','reason'=>'required|string|min:5|max:500','request_id'=>'required|uuid']);return response()->json($this->inventory->repeat($invoice,(int)$v['invoice_test_rel_id'],$r->user(),$v['reason'],$v['request_id']),201);}
}